export const REQUEST_TYPE_DYNASTY_LIST = 'REQUEST_TYPE_DYNASTY_LIST';
export const FETCH_TYPE_DYNASTY_LIST = 'FETCH_TYPE_DYNASTY_LIST';
export const RECEIVE_TYPE_DYNASTY_LIST = 'RECEIVE_TYPE_DYNASTY_LIST';

export const REQUEST_TYPE_AUTHOR_LIST = 'REQUEST_TYPE_AUTHOR_LIST';
export const FETCH_TYPE_AUTHOR_LIST = 'FETCH_TYPE_AUTHOR_LIST';
export const RECEIVE_TYPE_AUTHOR_LIST = 'RECEIVE_TYPE_AUTHOR_LIST';

export const REQUEST_TYPE_BOOK_LIST = 'REQUEST_TYPE_BOOK_LIST';
export const FETCH_TYPE_BOOK_LIST = 'FETCH_TYPE_BOOK_LIST';
export const RECEIVE_TYPE_BOOK_LIST = 'RECEIVE_TYPE_BOOK_LIST';

export const REQUEST_TYPE_THEME_LIST = 'REQUEST_TYPE_THEME_LIST';
export const FETCH_TYPE_THEME_LIST = 'FETCH_TYPE_THEME_LIST';
export const RECEIVE_TYPE_THEME_LIST = 'RECEIVE_TYPE_THEME_LIST';


export const REQUEST_BOOK_MENU_LIST = 'REQUEST_BOOK_MENU_LIST';
export const FETCH_BOOK_MENU_LIST = 'FETCH_BOOK_MENU_LIST';
export const RECEIVE_BOOK_MENU_LIST = 'RECEIVE_BOOK_MENU_LIST';

export const REQUEST_BOOK_MENU_DETAIL = 'REQUEST_BOOK_MENU_DETAIL';
export const FETCH_BOOK_MENU_DETAIL = 'FETCH_BOOK_MENU_DETAIL';
export const RECEIVE_BOOK_MENU_DETAIL = 'RECEIVE_BOOK_MENU_DETAIL';

export const REQUEST_AUTHOR_DETAIL = 'REQUEST_AUTHOR_DETAIL';
export const FETCH_AUTHOR_DETAIL = 'FETCH_AUTHOR_DETAIL';
export const RECEIVE_AUTHOR_DETAIL = 'RECEIVE_AUTHOR_DETAIL';

export const REQUEST_DYNASTY_DETAIL = 'REQUEST_DYNASTY_DETAIL';
export const FETCH_DYNASTY_DETAIL = 'FETCH_DYNASTY_DETAIL';
export const RECEIVE_DYNASTY_DETAIL = 'RECEIVE_DYNASTY_DETAIL';

export const REQUEST_THEME_DETAIL = 'REQUEST_THEME_DETAIL';
export const FETCH_THEME_DETAIL = 'FETCH_THEME_DETAIL';
export const RECEIVE_THEME_DETAIL = 'RECEIVE_THEME_DETAIL';


